name: synapse-ci-cd-dev-$(rev:r)

trigger:
  # none
  branches:
    include:
      - 'main'
      - 'master'
  paths:
    exclude:
      - .ado/*
pr:
  none


variables:
  - name: ARTIFACTS_FOLDER
    value: "./synapse" # Update to '{yourResourceManagerConnectionName}'
  - name: AZURE_RESOURCE_MANAGER_CONNECTION_NAME
    value: "azure-devops-service-connection" # Update to '{yourResourceManagerConnectionName}'
  - name: RESOURCE_GROUP_NAME_DEV
    value: "" # Update to '{yourRESOURCE_GROUP_NAME}'
  - name: WORKSPACE_NAME_DEV
    value: "" # Update to '{yourWORKSPACE_NAME_DEV}'

stages:
  - stage: Build
    displayName: "PublishArtifact "
    jobs:
      - job: Build
        displayName: "Build Synapse artifact "
        continueOnError: false
        pool:
          vmImage: "ubuntu-latest"
        steps:
          # Checkout code
          - checkout: self
            name: checkout_repository
            displayName: Checkout repository
            submodules: true
            lfs: false
            clean: true
            continueOnError: false
            enabled: true
          - task: Synapse workspace deployment@2
            inputs:
              TargetWorkspaceName: 'dev'
              ArtifactsFolder: $(ARTIFACTS_FOLDER)
              operation: 'validate'
          - task: CopyFiles@2
            displayName: 'Copy Files to:  $(build.artifactstagingdirectory)'
            inputs:
              Contents: |
                ExportedArtifacts/*
                TemplateParametersForWorkspace*.json
              flattenFolders: true
              TargetFolder: ' $(build.artifactstagingdirectory)'

          - publish: ' $(build.artifactstagingdirectory)'
            displayName: 'Publish synapse'
            artifact: 'synapse_template'

  - stage: Deploy_dev
    displayName: "Deploy Synapse to dev"
    dependsOn: Build
    # condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
    jobs:    
    - template: templates/jobs/synapse-deploy-job.yml
      parameters:
        ENVIRONMENT_NAME: 'dev'
        TARGET_WORKSPACE_NAME: $(WORKSPACE_NAME_DEV)
        TARGET_RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME_DEV)
        PARAMETER_FILEPATH: synapse_template/TemplateParametersForWorkspace_dev.json
        DEPLOY_FILEPATH: synapse_template/TemplateForWorkspace.json
        IS_RESTART_TRIGGER: false
        